FLATPAGES_ROOT = 'templates/help'
FLATPAGES_EXTENSION = '.md'
FLATPAGES_AUTO_RELOAD = True

MAIL = False
MAIL_USE_TLS = True
MAIL_SERVER = ''
MAIL_USE_SSL = False
MAIL_USERNAME = ''
MAIL_PASSWORD = ''

USE_MYSQL = True
MYSQL_HOST = ''
MYSQL_USERNAME = ''
MYSQL_PASSWORD = ''
MYSQL_DATABASE = ''
